- name: Install Apache web server (Redhat/CentOS)
  yum: pkg={{ redhat_apache }} state=latest
  when: "ansible_os_family == 'RedHat'"
  notify: Restart HTTPD
  ignore_errors: yes

- name: Install Apache web server (Debian/Ubuntu)
  yum: name={{ debian_apache }} state=latest
  when: "ansible_os_family == 'Debian'"
  notify: Restart Apache
  ignore_errors: yes
