--- # 
- hosts: redhat
  remote_user: schalla
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Executing below command
      command: /usr/sbin/setenforce 0
      #command: /home/schalla/test.sh
      #args:
      #  chdir: /home/schalla/
