--- # COPY MODULE
- hosts: redhat
  remote_user: schalla
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Copying file from this server to destination server location
      copy: 
        src: files/test1 
        dest: /home/schalla/test1 
        owner: schalla 
        group: schalla 
        mode: 700
