--- # GET_URL Module Example
- hosts: redhat
  remote_user: schalla
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Get and download the init fule from the web server
      get_url: url=http://srinathrchalla2.mylabserver.com/mytest.ini dest=/home/schalla/mytest.ini mode=0440
