--- # SERVICE MODULE
- hosts: redhat
  remote_user: schalla
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install Web Server
      yum: name=httpd state=installed
    - name: Start the service
      service: name=httpd state=started
    - name: Enable the service
      service: name=httpd enabled=yes
