--- # SHELL Module
- hosts: redhat
  remote_user: schalla
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Executing remote command - uptime
      shell: /usr/bin/uptime >> /home/schalla/uptime.log
      #args:
      #  chdir: logs/
      #  creates: uptime.log
