--- # 
- hosts: redhat
  remote_user: schalla
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Echo'ing the o/p in stdout and stderr format
      command: echo 'Hello World'
      register: result
    - debug: msg={{ result.stdout }}
    - debug: msg={{ result.stderr }}
    - shell: cat /etc/motd
      register: motd
    - debug: msg={{ motd.stdout }}
    - debug: msg="MOTD file is empty"
      when: motd.stdout == ""

