--- # 
- hosts: redhat
  remote_user: schalla
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Installaing Apache tomcat
      action: yum name=tomcat state=installed
    - name: Waiting for Port 8080 to listen
      wait_for:
        port: 8080
        state: started
    - name: verifying lynx installation
      action: yum name=lynx state=installed
