--- # Master Playbook for Web Servers
- hosts: redhat 
  remote_user: schalla
  become: yes
  connection: ssh
  pre_tasks:
  - name: Role execution start time
    raw: date > /home/schalla/role_start_time.log
  roles:
    - redhat_webservers
  post_tasks: 
  - name: Role END time
    raw: date > /home/schalla/role_end_time.log
