--- # 
- hosts: apacheweb 
  remote_user: schalla
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: ping app server before we run our install
      local_action: command ping -c 4 srinathrchalla2
    - name: Install Lynx on Remote server
      yum: pkg=lynx state=latest
