--- # My first YAML Playbook for Ansible
- hosts: apacheweb
  user: schalla
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1a
  vars_files:
    - conf/copyrights.yaml
    - conf/webdefaults.yaml
  vars_prompt:
    - name: web_domain
      prompt: Web Domain
  tasks:
    - name: Install Lynx Web Browser
      action: yum name=lynx state=installed
    - name: Check for Telnet Client
      action: yum name=telnet state=absent 
