--- # Optimized Playbook
- hosts: apacheweb
  remote_user: schalla
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Start Time of this Process
      command: /usr/bin/date
      register: timestamp_start
    - debug: var=timestamp_start

    # Install Apache WebServer and restart the service

    - name: Install Apache Web Server
      yum: pkg=httpd state=installed
      notify: Start HTTPD
 
    #- name: Verify Service is Running?
    #  command: systemctl status httpd
    #  register: result
    #- debug: var=result
     
    # Install Telnet and Lynx browser

    - name: Install Telnet client software
      yum: pkg=telnet state=latest

    - name: Install LYNX Software
      yum: pkg=lynx state=latest

    - name: Log all the packages install on the system
      command: yum list installed 
      register: installed_result
    - debug: var=installed_result

    - name: End Time of the playbook run
      command: /usr/bin/date
      register: endtime
    - debug: var=endtime
    
  handlers:
      - name: Start HTTPD
        service: name=httpd state=started

