--- # 
- hosts: redhat
  remote_user: schalla
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install telnet
      yum: pkg=telnet state=latest
    - name: Install Lynx
      yum: pkg=lynx state=latest
    - name: List Home
      command: ls -la /home/schalla
      register: result
    - debug: var=result

