--- # tags. Run it as  # ansible-playbook tags.yaml --tags packages
- hosts: redhat
  remote_user: schalla
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install the telnet and lynx packages
      yum: pkg={{ item }} state=latest
      with_items:
        - lynx
        - telnet
      tags:
        - packages
    - name: Verify that telnet was installed
      raw: yum list installed | grep telnet > /home/schalla/pkg.log
      tags:
        - verify
